### ISSUE TITLE
QNetworkConfiguration is deprecated

### ISSUE THREAD

**Issue by z3ntu** [ubports/ubuntu-download-manager#28] opened 2020-10-13 15:00 UTC
This gets used a lot here and is scheduled to be removed with Qt 6 afaik.

**Comment by dobey** [comment] 2020-10-13 18:24
Qt 6 is not going to have the vast majority of modules we need for a long time, so I don't think this is a problem. As I understand, Qt 6 is breaking API in a big way again, so probably most of UT would need some large changes to get things working on it. I don't think we need issues about Qt 6 to be open yet. It's not going to be on our roadmap for a long time.

**Comment by UniversalSuperBox** [comment] 2021-06-08 16:34
Duplicate of https://gitlab.com/ubports/core/lomiri-download-manager/-/issues/1. Since we're moving to GitLab anyway, that report is preferable.

**Closed as completed by UniversalSuperBox** 2021-06-08 16:34 UTC
